### ISSUE TITLE
Console Error "VueDarkMode is not defined"

### ISSUE THREAD

**Issue by kabanoki** [LeCoupa/vuesocial#3]
Hello
When I use "VUE SOCIAL" with a CDN, I get a title error.
How should I solve it?
Please check the following Github source for the tried source code.
[https://github.com/kabanoki/vue/blob/master/vuesocial/index.html](https://github.com/kabanoki/vue/blob/master/vuesocial/index.html)

**Comment by LeCoupa** [comment]
Hello @kabanoki, can you try to import Vue Dark Mode with your CDN also?

https://www.growthbunker.dev/vuedarkmode/

`<script src="https://cdn.jsdelivr.net/npm/@growthbunker/vuedarkmode@latest/dist/vuedarkmode.min.js"></script>
`
I recommend to use the NPM package if this is a possible solution for you though.
